build 0.20.rc

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -4,42 +4,62 @@
 language: generic
 
 os: osx
-osx_image: beta-xcode6.1
+osx_image: xcode6.4
 
 env:
   matrix:
-    
-    - CONDA_NPY=110  CONDA_PY=27
-    - CONDA_NPY=111  CONDA_PY=27
-    - CONDA_NPY=110  CONDA_PY=34
-    - CONDA_NPY=111  CONDA_PY=34
-    - CONDA_NPY=110  CONDA_PY=35
-    - CONDA_NPY=111  CONDA_PY=35
+    - CONFIG=osx_python2.7
+    - CONFIG=osx_python3.5
+    - CONFIG=osx_python3.6
+
   global:
     # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
-    - secure: "cXmMh0qV5bhXevVtdcMf8VOVIG0zOA0cQRihCsOaDG0yPSP1tW0N40llDkDhjk80wIKMMzuwofaarESzW5i5+GTbvDMmzpeHZAEoXYUIsNTxNJMX7KcvxNdeVIGNM8tcM3a4Zp/u0cvOjDs6xSHeZPdNit3x8rDaARASwU+YZnIIY8Iieizo3LmWxRghjOdFYnr0frOshy38PI+l1ywYqsN/L8+4GqxWtkTuzK3fnI3MlwfDC8tVImjXuukHK3J78SsDdnbTBJlV0tcNV8iGa08Md55bgv9HEgFbHRSunc22lLjFRHMT10Hvl0H0HdylYkQTKC7iOwIw9D3kIp4uR+g0rDKzBuuYF+jV65+UhR5TKMiH4QIiMxBMLpB8QU1Ey58L2X2t1j06d+VZYp2UiubGNvxjXun9tWFnIotFoho1bfW0gUURNvk+fEs0O/0LpReTweNVJLc1JakT7eitFm5gaV8CNzAsNcBCpPsHWiCMQm+FD3D57q+DIJ4ONl0OOBYSDNkziJEvgB0XyV7UpGobm0xu/JTPg+Qq2op3GDxgCfILqhApTEVkMKQJv+o5yHO/JIonxCbE41xIotw8JjhQ2VROFLPGh3F3buiJ26VUbI41yoN20D4y0Bvj7HPdiBHVWNcUmkj1xYZckivnxjCE5eth/TBJiK9gqjgRw6w="
+    - secure: "xHG5feKFSl87s9IK6ReTanlNhHkXp4xw5+pdNJxXzpUOHhhDznnJj7+929IxeEuoHJToVty+6BpbLOZGC4B/EirIxY7csjf5ymWHrcTo/hfQ5PL3nlTseoL5l2p2pPwFvzrBREt0O5BBCeiM2rMbr2m814d+mx/VSXvFttfrBbrK3Yn2aU4xdyU0Ce2Rap7QMO9PGwvb1quZWfdyD4DGVx3v6qap+L9IPmOUzJ+Iut58EXD04h3yfdKYulcqv7rlAlQJWokqrlKBsKfRlbP1MaYnKPkx2fcsCneH+8ItJCjoHnTRcGVj6kC6PtQP5cQkScWcWLJPzGhggAywgoTqAGTaGkxm/zEMbObXQGhnEgFcQaD5kn6lEkRFlggobVMDPf8C6wanXqh037So0Qyn/IFqDE5/YyhqPfM2/dgeu7VKEqhqqtK/1/pUiicmDMCKLIbCN9v7aYylZMVWi9BDxubP0hyNz/PssCdu6XmSwwUGgsZVr3JqXWPWX4mskwnny1S45BDzdj1dZaRCeWnzhdN1NeooBZWFH6LW9ojD014rD58TejscKYQkZfOlgbAG5lj4fD8urEBdp8ntLySJywN2gCpbFzvBkyBen6ilDgp5A0H3mOEohPEV53q9XdIXbayeLK524B/eLGmN5s2vpGNh4Hdm0CKg0TYRfwxhWU4="
 
 
 before_install:
+    # Fast finish the PR.
+    - |
+      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
+          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1
+
     # Remove homebrew.
-    - brew remove --force $(brew list)
-    - brew cleanup -s
-    - rm -rf $(brew --cache)
+    - |
+      echo ""
+      echo "Removing homebrew from Travis CI to avoid conflicts."
+      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
+      chmod +x ~/uninstall_homebrew
+      ~/uninstall_homebrew -fq
+      rm ~/uninstall_homebrew
+
 
 install:
+    # Install Miniconda.
     - |
+      echo ""
+      echo "Installing a fresh version of Miniconda."
       MINICONDA_URL="https://repo.continuum.io/miniconda"
       MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
       curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
       bash $MINICONDA_FILE -b
 
+    # Configure conda.
+    - |
+      echo ""
+      echo "Configuring conda."
       source /Users/travis/miniconda3/bin/activate root
-      conda config --add channels conda-forge
-      conda config --set show_channel_urls true
-      conda install --yes --quiet conda-forge-build-setup
+
+      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
+      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml
+
       source run_conda_forge_build_setup
 
-script:
-  - conda build ./recipe
+    # compiler cleanup
+    - |
+      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml
 
-  - upload_or_check_non_existence ./recipe conda-forge --channel=rc
+script:
+  # generate the build number clobber
+  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
+  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
+  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
